'use strict';
const test = require('node:test'); const assert = require('node:assert/strict');
const { TaskRouter, classifyTask, planWorkflow } = require('./task-router');
const { ProviderHealthManager } = require('./provider-health'); const { ProviderPerformanceStore } = require('./provider-performance');
function setup(config = {}, availability = {}) { const cfg = { OrchestrateCliList: ['a', 'b', 'c'], ...config }; const h = new ProviderHealthManager({ getConfig: () => cfg, availability }); h.providers = { a: { id: 'a', enabled: true, available: true, health: 'healthy', costTier: 5, speedTier: 2, qualityTier: 5, supportsRepo: true, supportsCodeChanges: true, supportsLongRunning: false, roles: { coder: { priorCapability: 5 }, reviewer: { priorCapability: 2 } } }, b: { id: 'b', enabled: true, available: true, health: 'healthy', costTier: 1, speedTier: 5, qualityTier: 3, supportsRepo: true, supportsCodeChanges: true, supportsLongRunning: false, roles: { coder: { priorCapability: 2 }, reviewer: { priorCapability: 5 } } }, c: { id: 'c', enabled: true, available: true, health: 'healthy', costTier: 2, speedTier: 5, qualityTier: 3, supportsRepo: true, supportsCodeChanges: true, supportsLongRunning: true, roles: { investigator: { priorCapability: 4 } } } }; const p = new ProviderPerformanceStore(); return { h, p, r: new TaskRouter({ health: h, performance: p, getConfig: () => cfg }) }; }
test('classifies roles and plans ordered workflow', () => { const c = classifyTask({ prompt: 'investigate, code, test and review the dashboard' }); assert.ok(c.roles.includes('investigator')); assert.ok(c.roles.includes('coder')); assert.ok(c.roles.includes('tester')); assert.ok(c.roles.includes('reviewer')); assert.deepEqual(planWorkflow({ prompt: 'investigate, code, test and review' }).map(x => x.role), ['investigator', 'coder', 'tester', 'reviewer']); });
test('role performance is independent and changes selection', () => { const { r, p } = setup(); assert.equal(r.selectProvider({ prompt: 'implement code', role: 'coder' }).provider, 'a'); assert.equal(r.selectProvider({ prompt: 'review code', role: 'reviewer' }).provider, 'b'); for (let i = 0; i < 10; i++) p.record('a', 'reviewer', { ok: true }); assert.equal(r.selectProvider({ prompt: 'review code', role: 'reviewer' }).provider, 'a'); });
test('quality wins on complex work and economy prefers cheaper threshold provider', () => { const { r } = setup(); assert.equal(r.selectProvider({ prompt: 'complex architecture implementation', role: 'coder', complexity: 'high', qualityRequirement: 'high' }, { policy: 'QUALITY' }).provider, 'a'); assert.equal(r.selectProvider({ prompt: 'summarize this', role: 'summarizer' }, { policy: 'ECONOMY' }).provider, 'b'); });
test('speed, health and cooldown affect eligibility', () => { const { r, h } = setup(); assert.equal(r.selectProvider({ prompt: 'investigate quickly', role: 'investigator' }, { policy: 'SPEED' }).provider, 'c'); h.providers.c.cooldownUntil = Date.now() + 10000; assert.notEqual(r.selectProvider({ prompt: 'investigate quickly', role: 'investigator' }, { policy: 'SPEED' }).provider, 'c'); h.providers.b.enabled = false; assert.notEqual(r.selectProvider({ prompt: 'investigate quickly', role: 'investigator' }).provider, 'b'); });
test('writer and reviewer prefer independent capable provider', () => { const { r } = setup(); const x = r.selectProvider({ prompt: 'review implementation', role: 'reviewer', authorProvider: 'a' }); assert.equal(x.provider, 'b'); assert.equal(x.reviewIndependence, true); const y = r.selectProvider({ prompt: 'review implementation', role: 'reviewer', authorProvider: 'b' }, { exclude: ['a', 'c'] }); assert.equal(y.reviewIndependence, false); });
test('performance store ignores infrastructure failures and smooths cold start', () => { const p = new ProviderPerformanceStore(); p.record('a', 'coder', { ok: false, errorType: 'QUOTA_EXHAUSTED' }); assert.equal(p.get('a', 'coder').attempts, 0); p.record('a', 'coder', { ok: false, errorType: 'TASK_ERROR' }); assert.equal(p.get('a', 'coder').failures, 1); p.record('a', 'coder', { ok: true }); assert.equal(p.get('a', 'coder').successes, 1); });
