'use strict';
const { ProviderHealthManager } = require('./provider-health');
const { classifyTask, planWorkflow } = require('./task-roles');
const n = (v, fallback = 0) => Number.isFinite(Number(v)) ? Number(v) : fallback;
function inferTask(task = {}) { const c = classifyTask(task); const caps = new Set(task.capabilities || []); if (c.roles.includes('reviewer') || c.roles.includes('security-reviewer')) caps.add('review'); if (c.roles.some(r => ['coder', 'debugger', 'tester'].includes(r))) caps.add('coding'); if (c.characteristics.repoReadRequired) caps.add('repo-edit'); if (c.characteristics.longRunning) caps.add('long-running'); if (c.characteristics.costSensitivity === 'high') caps.add('cheap-tasks'); return { capabilities: [...caps], needsRepo: c.characteristics.repoReadRequired, longRunning: c.characteristics.longRunning, review: c.roles.includes('reviewer') || c.roles.includes('security-reviewer'), complexity: c.characteristics.complexity, quality: c.characteristics.qualityRequirement, roles: c.roles, characteristics: c.characteristics }; }
function policyOf(task, config, options) { return String(options.policy || task.routingPolicy || config.AutoRoutingPolicy || 'BALANCED').toUpperCase(); }
class TaskRouter {
  constructor({ health, performance, getConfig = () => ({}) } = {}) { this.health = health || new ProviderHealthManager({ getConfig }); this.performance = performance; this.getConfig = getConfig; }
  selectProvider(task = {}, options = {}) {
    const inferred = inferTask(task); const role = options.role || task.role || inferred.roles[0]; const config = this.getConfig() || {}; const policy = policyOf(task, config, options); const excluded = new Set(options.exclude || []); const preferred = options.preferredProvider || task.preferredProvider || config.PreferredProvider; const candidates = Object.values(this.health.providers).filter(p => !excluded.has(p.id) && this.health.isAvailable(p.id, { manual: false })); const threshold = inferred.characteristics.qualityRequirement === 'high' || inferred.characteristics.complexity === 'high' ? 3 : 1;
    const scored = candidates.map(p => { const profile = (p.roles && p.roles[role]) || {}; const history = this.performance && this.performance.get(p.id, role) || {}; const samples = n(history.attempts); const success = (n(history.successes) + 1) / (samples + 2); const prior = n(profile.priorCapability || profile.capability || p.qualityTier, 1) / 5; const confidence = Math.min(1, samples / 10); const roleScore = prior * (1 - confidence) + success * confidence; let score = roleScore * 100; const reasons = [`${role} role fit`, samples ? `${samples} measured ${role} result(s)` : 'cold-start prior']; if (n(profile.qualityTier || p.qualityTier, 1) < threshold && (role === 'security-reviewer' || inferred.characteristics.complexity === 'high')) { score -= 1000; reasons.push('below quality gate'); } if (inferred.characteristics.repoReadRequired && !p.supportsRepo) score -= 1000; if (inferred.characteristics.repoWriteRequired && !p.supportsCodeChanges) score -= 400; if (inferred.characteristics.longRunning) score += p.supportsLongRunning ? 120 : -90; if (policy === 'QUALITY') score += n(p.qualityTier, 1) * 12; if (policy === 'ECONOMY' || inferred.characteristics.costSensitivity === 'high') score += (6 - n(p.costTier, 3)) * 30; if (policy === 'SPEED' || inferred.characteristics.latencySensitivity === 'high') score += n(p.speedTier, 3) * 12; if (inferred.characteristics.complexity === 'high' || inferred.characteristics.qualityRequirement === 'high') score += n(p.qualityTier, 1) * 18; if (role === 'summarizer' && (p.capabilities || []).includes('cheap-tasks')) score += 100; score -= n(history.reworkEvents) * 5 + n(p.consecutiveFailures) * 8; if (preferred === p.id) { score += 1000; reasons.push('user preference'); } const author = options.authorProvider || task.authorProvider || task.writerProvider; if ((role === 'reviewer' || role === 'security-reviewer') && author) { if (author !== p.id) { score += 25; reasons.push('independent from author'); } else { score -= 25; reasons.push('self-review fallback'); } } return { provider: p.id, score: Math.round(score * 100) / 100, roleScore: Math.round(roleScore * 1000) / 1000, health: p.health, excluded: false, reasons }; }).sort((a, b) => b.score - a.score); if (!scored.length || scored[0].score < -500) throw new Error(`No compatible providers are currently available for role ${role}`); const selected = scored[0]; const author = options.authorProvider || task.authorProvider || task.writerProvider; return { provider: selected.provider, selectedProvider: selected.provider, selectedRole: role, score: selected.score, routingScore: selected.score, reason: selected.reasons, routingReason: selected.reasons, candidates: scored, routingCandidates: scored, policy, roles: inferred.roles, characteristics: inferred.characteristics, reviewIndependence: role === 'reviewer' || role === 'security-reviewer' ? !!author && selected.provider !== author : undefined, workflow: options.plan ? planWorkflow(task) : undefined };
  }
}
module.exports = { TaskRouter, inferTask, classifyTask, planWorkflow };
